"""Bundle the current default SVG faces; no image decoding or per-card requests."""
from pathlib import Path
import json

root = Path(__file__).resolve().parent.parent
faces = {p.stem: p.read_text(encoding="utf-8") for p in sorted((root / "dist/assets/cards").glob("*.svg"))}
(root / "dist/card-faces.js").write_text(
    "/* Generated by scripts/bundle-cards.py. */\nwindow.CardFaces="
    + json.dumps(faces, ensure_ascii=False, separators=(",", ":")) + ";\n",
    encoding="utf-8",
)
