const assert=require('node:assert/strict');
const K=require('../dist/engine.js');
const clone=g=>JSON.parse(JSON.stringify(g));
const t=(index,card)=>({type:'tableau',index,card});
const dest=index=>({type:'tableau',index});
let seed=87;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);
let cases=0;const test=(name,fn)=>{fn();cases++;console.log('PASS '+name);};
const create=()=>K.create(1,random,'cheat');
function layout(g){g.stock.push(...g.tableau.flat());g.stock.forEach(c=>c.up=false);g.tableau=Array.from({length:7},()=>[]);}
function take(g,suit,rank){const i=g.stock.findIndex(c=>c.suit===suit&&c.rank===rank);assert(i>=0);const c=g.stock.splice(i,1)[0];c.up=true;return c;}
test('Normal and legacy saves remain valid; normal games reject every cheat',()=>{const g=K.create();assert(K.valid(g));delete g.mode;assert(K.valid(g));const before=clone(g);for(const a of ['destroy','swap','joker'])assert(!K.cheat(g,a,t(0,0),dest(1)));assert.deepEqual(g,before);});
test('Destroy reveals hidden card; undo snapshot restores card and charge; limits are enforced',()=>{const g=create(),before=clone(g),c=g.tableau[6].at(-1);assert(K.cheat(g,'destroy',t(6,6)));assert.deepEqual(g.removed,[c]);assert(g.tableau[6].at(-1).up);assert.equal(g.cheats.destroy,2);assert.equal(K.completed(g),1);assert(K.valid(g));assert(K.valid(before));assert.equal(before.tableau[6].length,7);assert.equal(before.cheats.destroy,3);assert(K.cheat(g,'destroy',t(6,5)));assert(K.cheat(g,'destroy',t(6,4)));const final=clone(g);assert(!K.cheat(g,'destroy',t(6,3)));assert.deepEqual(g,final);assert(K.valid(g));});
test('Destroyed foundation ranks are skipped; removing from foundation restores next expected rank',()=>{const g=create();layout(g);g.tableau[0]=[take(g,'S',1)];g.tableau[1]=[take(g,'S',3)];g.tableau[2]=[take(g,'S',2)];g.tableau[3]=[take(g,'S',4)];assert(K.cheat(g,'destroy',t(0,0)));assert(K.cheat(g,'destroy',t(1,0)));assert(K.move(g,t(2,0),{type:'foundation',index:0}));assert.equal(K.nextRank(g,0),4);assert(K.move(g,t(3,0),{type:'foundation',index:0}));g.tableau[4]=[take(g,'H',5)];assert(K.move(g,{type:'foundation',index:0,card:1},dest(4)));assert.equal(K.nextRank(g,0),4);assert(K.valid(g));});
test('Swap changes only two face-up cards and rejects hidden, foundation and same-card targets',()=>{const g=create(),a={...g.tableau[0][0]},b={...g.tableau[6][6]};assert(K.cheat(g,'swap',t(0,0),t(6,6)));assert.deepEqual(g.tableau[0][0],b);assert.deepEqual(g.tableau[6][6],a);assert.equal(g.cheats.swap,2);const snap=clone(g);for(const from of [t(6,0),t(99,0),{type:'foundation',index:0,card:0},null])assert(!K.cheat(g,'swap',from,t(0,0)));assert(!K.cheat(g,'swap',t(0,0),t(0,0)));assert.deepEqual(g,snap);assert(K.valid(g));});
test('Broken sequences from cheats cannot move as a group',()=>{const g=create();layout(g);g.tableau[0]=[take(g,'S',9),take(g,'H',8),take(g,'C',7)];assert(K.cheat(g,'destroy',t(0,1)));assert.equal(K.movable(g,t(0,0)).length,0);assert.equal(K.movable(g,t(0,1)).length,1);assert(K.valid(g));});
test('Jokers are wildcard tableau bridges, never foundations, and have stable unique IDs',()=>{const g=create();layout(g);g.tableau[0]=[take(g,'H',3)];g.tableau[1]=[take(g,'S',11)];assert(K.cheat(g,'joker',null,dest(0)));assert(K.move(g,t(1,0),dest(0)));assert(K.linked(g.tableau[0][0],g.tableau[0][1]));assert.equal(K.movable(g,t(0,1)).length,2);assert(K.move(g,t(0,1),dest(2)));assert(K.cheat(g,'joker',null,dest(1)));assert.notEqual(K.id(g.tableau[1][0]),K.id(g.tableau[2][0]));assert(!K.canMove(g,t(1,0),{type:'foundation',index:0}));assert(!K.cheat(g,'joker',null,dest(3)));assert(K.valid(g));assert(K.cheat(g,'destroy',t(1,0)));assert.equal(K.completed(g),0);assert(K.valid(g));});
test('Jokers swapped to waste survive stock recycling and save restore',()=>{const g=create();K.draw(g);assert(K.cheat(g,'joker',null,dest(0)));assert(K.cheat(g,'swap',t(0,1),{type:'waste',index:0,card:0}));while(g.stock.length)K.draw(g);K.draw(g);assert(g.stock.some(K.isJoker));assert(K.valid(JSON.parse(JSON.stringify(g))));});
test('Cheat win counts destroyed ordinary cards but does not require jokers',()=>{const g=create();layout(g);g.tableau[0]=[take(g,'S',13)];assert(K.cheat(g,'destroy',t(0,0)));assert(K.cheat(g,'joker',null,dest(1)));g.foundations=K.suits.map(s=>g.stock.filter(c=>c.suit===s).sort((a,b)=>a.rank-b.rank).map(c=>({...c,up:true})));g.stock=[];assert(K.valid(g));assert(K.win(g));assert.equal(K.completed(g),52);g.waste.push(g.foundations[0].pop());assert(K.valid(g));assert(!K.win(g));});
test('Malformed cheat saves reject bad budgets, missing/duplicate cards and forged jokers',()=>{const g=create();for(const edit of [h=>h.cheats.destroy=-1,h=>h.cheats.swap=4,h=>h.stock.pop(),h=>h.removed.push(h.stock[0]),h=>h.tableau[0].push({suit:'J',rank:1,up:true}),h=>h.mode='normal']){const h=clone(g);edit(h);assert(!K.valid(h));}});
test('Mixed cheats and legal moves preserve save validity for both draw modes',()=>{for(let n=0;n<30;n++){const g=K.create(n%2?1:3,random,'cheat');for(let i=0;i<160;i++){const targets=g.tableau.flatMap((p,index)=>p.flatMap((c,card)=>c.up?[t(index,card)]:[]));if(g.waste.length)targets.push({type:'waste',index:0,card:g.waste.length-1});const pick=()=>targets[Math.floor(random()*targets.length)];const action=['destroy','swap','joker'][Math.floor(random()*3)];if(i%4===0)K.cheat(g,action,pick(),action==='joker'?dest(Math.floor(random()*7)):pick());else{const opts=K.options(g);if(opts.length&&random()>.3){const o=opts[Math.floor(random()*opts.length)];K.move(g,o.from,o.to);}else K.draw(g);}assert(K.valid(g),'invalid mixed state');assert(K.valid(clone(g)));}}});
console.log(cases+' cheat rule groups passed.');
