const assert=require('node:assert/strict');
const K=require('../dist/engine.js');
const clone=g=>JSON.parse(JSON.stringify(g));
const t=(index,card)=>({type:'tableau',index,card});
const pocket=card=>({type:'pocket',index:0,card});
const dest=index=>({type:'tableau',index});
const foundation=index=>({type:'foundation',index});
let seed=87;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);
let cases=0;const test=(name,fn)=>{fn();cases++;console.log('PASS '+name);};
const create=()=>K.create(1,random,'cheat');
function layout(g){g.stock.push(...g.tableau.flat());g.stock.forEach(c=>c.up=false);g.tableau=Array.from({length:7},()=>[]);}
function take(g,suit,rank){const i=g.stock.findIndex(c=>c.suit===suit&&c.rank===rank);assert(i>=0);const c=g.stock.splice(i,1)[0];c.up=true;return c;}
function legacy(){const g=create();delete g.pocket;g.removed=[];g.cheats.destroy=3;return g;}
test('Normal and legacy normal saves stay valid and reject cheats',()=>{const g=K.create();delete g.mode;const before=clone(g);for(const a of ['pocket','destroy','swap','joker'])assert(!K.cheat(g,a,t(0,0),dest(1)));assert.deepEqual(g,before);assert.deepEqual(K.restore(g),g);assert(!K.move(g,pocket(0),dest(0)));});
test('Pocket stores three singles, reveals hidden cards and rejects a fourth atomically',()=>{const g=create(),before=clone(g);for(let i=6;i>=4;i--)assert(K.cheat(g,'pocket',t(6,i)));assert.equal(g.pocket.length,3);assert(g.tableau[6].at(-1).up);assert.equal(K.completed(g),0);assert.equal(g.moves,3);assert(K.valid(g));assert(K.valid(before));assert.equal(before.pocket.length,0);const full=clone(g);assert(!K.cheat(g,'pocket',t(0,0)));assert.deepEqual(g,full);assert(!K.cheat(g,'destroy',t(0,0)));});
test('Any pocket card can return singly, honoring placement rules, and freed slots are reusable',()=>{const g=create();layout(g);g.tableau[0]=[take(g,'S',13),take(g,'H',12),take(g,'C',11)];for(let i=2;i>=0;i--)assert(K.cheat(g,'pocket',t(0,i)));const before=clone(g);assert(!K.move(g,pocket(0),dest(1)));assert.deepEqual(g,before);assert(K.move(g,pocket(2),dest(1)));assert.deepEqual(g.pocket.map(c=>c.rank),[11,12]);assert(K.move(g,pocket(1),dest(1)));assert(K.move(g,pocket(0),dest(1)));assert.equal(g.pocket.length,0);assert.deepEqual(g.tableau[1].map(c=>c.rank),[13,12,11]);for(let n=0;n<5;n++){assert(K.cheat(g,'pocket',t(1,2)));assert(K.move(g,pocket(0),dest(1)));}assert(K.valid(g));});
test('Pocket cards contribute hints and foundations never skip their ranks',()=>{const g=create();layout(g);g.tableau[0]=[take(g,'S',1)];g.tableau[1]=[take(g,'S',2)];assert(K.cheat(g,'pocket',t(0,0)));assert.equal(K.nextRank(g,0),1);assert(!K.move(g,t(1,0),foundation(0)));assert(K.options(g).some(o=>o.from.type==='pocket'&&o.to.type==='foundation'));assert(K.move(g,pocket(0),foundation(0)));assert(K.move(g,t(1,0),foundation(0)));assert.equal(K.completed(g),2);assert(K.valid(g));});
test('Pocket rejects hidden cards, stock, foundations, pocket and non-top waste',()=>{const g=create();K.draw(g);K.draw(g);const before=clone(g);for(const from of [null,t(6,0),t(99,0),pocket(0),{type:'stock',index:0,card:0},{type:'foundation',index:0,card:0},{type:'waste',index:0,card:0}])assert(!K.cheat(g,'pocket',from));assert.deepEqual(g,before);assert(K.cheat(g,'pocket',{type:'waste',index:0,card:1}));assert(K.valid(g));});
test('Removing the middle of a run breaks group moves, while singles still work',()=>{const g=create();layout(g);g.tableau[0]=[take(g,'S',9),take(g,'H',8),take(g,'C',7)];assert(K.cheat(g,'pocket',t(0,1)));assert.equal(K.movable(g,t(0,0)).length,0);assert.equal(K.movable(g,t(0,1)).length,1);assert(K.valid(g));});
test('Swap changes only two face-up cards and enforces its limit',()=>{const g=create(),a=clone(g.tableau[0][0]),b=clone(g.tableau[6][6]);assert(K.cheat(g,'swap',t(0,0),t(6,6)));assert.deepEqual(g.tableau[0][0],b);assert.deepEqual(g.tableau[6][6],a);const snap=clone(g);for(const from of [t(6,0),t(99,0),foundation(0),pocket(0),null])assert(!K.cheat(g,'swap',from,t(0,0)));assert(!K.cheat(g,'swap',t(0,0),t(0,0)));assert.deepEqual(g,snap);assert(K.cheat(g,'swap',t(0,0),t(6,6)));assert(K.cheat(g,'swap',t(0,0),t(6,6)));assert(!K.cheat(g,'swap',t(0,0),t(6,6)));assert(K.valid(g));});
test('Jokers are reusable via pocket, accept arbitrary cards, never enter foundations',()=>{const g=create();layout(g);g.tableau[0]=[take(g,'H',3)];g.tableau[1]=[take(g,'S',11)];assert(K.cheat(g,'joker',null,dest(0)));assert(K.move(g,t(1,0),dest(0)));assert(K.move(g,t(0,1),dest(2)));assert(K.cheat(g,'joker',null,dest(1)));assert(!K.cheat(g,'joker',null,dest(3)));assert(K.cheat(g,'pocket',t(1,0)));assert(!K.move(g,pocket(0),foundation(0)));assert(K.move(g,pocket(0),dest(4)));assert.equal(g.cheats.joker,0);assert(K.valid(g));});
test('Jokers swapped to waste survive recycling and save restore',()=>{const g=create();K.draw(g);assert(K.cheat(g,'joker',null,dest(0)));assert(K.cheat(g,'swap',t(0,1),{type:'waste',index:0,card:0}));while(g.stock.length)K.draw(g);K.draw(g);assert(g.stock.some(K.isJoker));assert(K.valid(K.restore(g)));});
test('Win requires all 52 ordinary cards in foundations; pocket jokers can remain',()=>{const g=create();layout(g);g.tableau[0]=[take(g,'S',13)];assert(K.cheat(g,'pocket',t(0,0)));assert(K.cheat(g,'joker',null,dest(1)));assert(K.cheat(g,'pocket',t(1,0)));g.foundations=K.suits.map(s=>g.stock.filter(c=>c.suit===s).sort((a,b)=>a.rank-b.rank).map(c=>({...c,up:true})));g.stock=[];assert(K.valid(g));assert.equal(K.completed(g),51);assert(!K.win(g));assert(K.move(g,pocket(0),foundation(0)));assert(K.win(g));assert(K.valid(g));assert.equal(g.pocket.length,1);});
test('Legacy destruction saves migrate without losing cards, moves, budgets or input data',()=>{const g=legacy();layout(g);g.removed=[take(g,'S',2),take(g,'H',1)];g.cheats.destroy=1;g.cheats.swap=2;g.moves=15;g.foundations[0]=[take(g,'S',1),take(g,'S',3),take(g,'S',4)];g.foundations[1]=[take(g,'H',2)];const original=clone(g),n=K.restore(g);assert(n);assert(K.valid(n));assert.deepEqual(g,original);assert.deepEqual(n.pocket.map(K.id),['S_02','H_A']);assert.deepEqual(n.foundations[0].map(c=>c.rank),[1]);assert.equal(n.foundations[1].length,0);assert.equal(n.moves,15);assert.equal(n.cheats.swap,2);for(const id of ['S_03','S_04','H_02'])assert(n.stock.some(c=>K.id(c)===id&&!c.up));assert.deepEqual(K.restore(n),n);const corrupt=clone(g);corrupt.stock.pop();assert.equal(K.restore(corrupt),null);});
test('Legacy destroyed joker is restored to pocket and old undo states are individually migratable',()=>{const g=legacy();const before=K.restore(g);g.cheats.joker=1;g.cheats.destroy=2;g.removed=[{suit:'J',rank:1,up:true}];const n=K.restore(g);assert(K.valid(n));assert(K.isJoker(n.pocket[0]));assert.equal(n.cheats.joker,1);assert(K.valid(before));assert.equal(before.pocket.length,0);assert.equal(before.cheats.joker,2);});
test('Malformed new saves reject oversized pockets, hidden cards, invalid budgets and duplicate cards',()=>{const g=create();for(const edit of [h=>h.cheats.swap=4,h=>h.stock.pop(),h=>h.pocket.push(h.stock[0]),h=>h.pocket=null,h=>h.pocket=Array.from({length:4},()=>{const c=h.stock.pop();c.up=true;return c}),h=>{h.pocket=[h.stock.pop()]},h=>h.tableau[0].push({suit:'J',rank:1,up:true}),h=>h.mode='normal',h=>h.removed=[]]){const h=clone(g);edit(h);assert(!K.valid(h));assert.equal(K.restore(h),null);}});
test('Mixed pocket, swap, joker and legal moves preserve 52 cards across both draw modes',()=>{for(let n=0;n<30;n++){const g=K.create(n%2?1:3,random,'cheat');for(let i=0;i<160;i++){const targets=g.tableau.flatMap((p,index)=>p.flatMap((c,card)=>c.up?[t(index,card)]:[]));if(g.waste.length)targets.push({type:'waste',index:0,card:g.waste.length-1});const pick=()=>targets[Math.floor(random()*targets.length)];const action=['pocket','swap','joker'][Math.floor(random()*3)];if(i%4===0)K.cheat(g,action,pick(),action==='joker'?dest(Math.floor(random()*7)):pick());else{const opts=K.options(g);if(opts.length&&random()>.3){const o=opts[Math.floor(random()*opts.length)];K.move(g,o.from,o.to);}else K.draw(g);}assert(K.valid(g),'invalid mixed state');assert(K.valid(K.restore(g)));}}});
console.log(cases+' cheat rule groups passed.');
